### ISSUE TITLE
TextView not working

### ISSUE THREAD

**Issue by vishiswoz** [CosmicMind/MaterialKit#114] opened 2016-01-06 16:12 UTC
I have a problem implementing the TextView, I'm getting an error on these lines (when setting the placeholder label of the TextView). There's some optimization error I get in the debugger log.

		textView.placeholderLabel = UILabel()
		textView.placeholderLabel!.textColor = MaterialColor.grey.base
		textView.placeholderLabel!.text = "Description"

**Comment by danieldahan** [comment] 2016-01-06 18:11
Hi @vishiswoz, I tried the TextView now and it seems to work. Please add the details of the device or simulator you are running it on, and the error console text. 

As well, it seems that this may be better suited for StackOverflow. We are moving implementation issues to Stack and only dealing with bugs here. Thanks!

**Comment by vishiswoz** [comment] 2016-01-06 22:30
Here is my code for the TextView, followed exactly like your example:
```
NSLayoutManager *layoutManager = [[NSLayoutManager alloc] init];
    NSTextContainer *textContainer = [[NSTextContainer alloc] initWithSize:self.view.bounds.size];
    text.delegate = self;
    [text.textStorage addLayoutManager:layoutManager];
    textView = [[TextView alloc] initWithTextContainer:textContainer];
    textView.delegate = self;
    textView.editable = true;
    textView.selectable = true;
    [textView setFont:[UIFont systemFontOfSize:20]];
    UILabel *label = [[UILabel alloc] init];
    [label setTextColor:[UIColor colorWithRed:158.0f/255.0f green:158.0f/255.0f blue:158.0f/255.0f alpha:1.0f]];
    [label setText:@"Choose Date"];
    //[textView setPlaceholderLabel:label];
    textView.titleLabel = [[UILabel alloc] init];
    [textView.titleLabel setFont:[UIFont systemFontOfSize:12]];
    textView.titleLabelColor = [UIColor colorWithRed:224.0f/255.0f green:224.0f/255.0f blue:224.0f/255.0f alpha:1.0f];
    textView.titleLabelActiveColor = [UIColor colorWithRed:41.0f/255.0f green:121.0f/255.0f blue:255.0f/255.0f alpha:1.0f];
    //[textView setFrame:CGRectMake(20, 315, 360, 30)];
    textView.translatesAutoresizingMaskIntoConstraints = false;
    [MaterialLayout alignToParent:self.view child:textView top:124.0f left:24.0f bottom:24.0f right:24.0f options:0];
    [self.view addSubview:activityName];
    [self.view addSubview:type];
    [self.view addSubview:textView];
```

**Comment by danieldahan** [comment] 2016-01-06 22:37
Are you using CocoaPods?

**Comment by vishiswoz** [comment] 2016-01-06 22:38
No i'm using Carthage

**Comment by danieldahan** [comment] 2016-01-06 22:47
Is Carthage compiling the framework in Release mode? If so, that would cause an issue, because optimization would be on. I checked the MaterialKit project and optimizations are off in debug mode and are on in Release mode.

**Comment by vishiswoz** [comment] 2016-01-06 23:51
How would I compile the framework using Carthage so it's not in release mode? I also turned off optimizations in my project as well.

**Comment by danieldahan** [comment] 2016-01-06 23:56
try this

carthage update --configuration debug

**Comment by vishiswoz** [comment] 2016-01-07 00:14
it didn't work i'm getting the same error

**Comment by danieldahan** [comment] 2016-01-07 00:20
I think I know what it is, I am making an update now to MaterialKit. One moment.

**Comment by danieldahan** [comment] 2016-01-07 00:35
try version 1.27.6

**Comment by vishiswoz** [comment] 2016-01-07 02:02
I'm getting an error on this line (EXC_BREAKPOINT):

```
p.hidden = !text.isEmpty
```

in here

```
	internal func handleTextViewTextDidChange() {
		if let p = placeholderLabel {
			p.hidden = !text.isEmpty
		}
		
		if 0 < text?.utf16.count {
			showTitleLabel()
			titleLabel?.textColor = titleLabelActiveColor
		} else if 0 == text?.utf16.count {
			hideTitleLabel()
		}
	}
```

**Comment by danieldahan** [comment] 2016-01-07 04:53
To solve the bad access I made an adjustment, try 1.27.7. As for the AutoLayout issue, in your code

```swift
[MaterialLayout alignToParent:self.view child:textView top:124.0f left:24.0f bottom:24.0f right:24.0f options:0];
    [self.view addSubview:textView];
```

You are setting the textView as a child after the AutoLayout constraints are being set. It should be done before. 

```swift
 [self.view addSubview:textView];
[MaterialLayout alignToParent:self.view child:textView top:124.0f left:24.0f bottom:24.0f right:24.0f options:0];
```

**Comment by vishiswoz** [comment] 2016-01-07 11:19
I have no errors now, so thank you for that, but now I can't physically see the textview, it's invisible. I can click on it and type text, but I cannot see the text or the title label or anything at all.

**Comment by danieldahan** [comment] 2016-01-07 18:36
try 1.27.8, I added the @objc.

**Comment by danieldahan** [comment] 2016-01-07 20:37
I am going to close this ticket. If the issue persists, please reopen it, or create a new one. All the best!

**Comment by vishiswoz** [comment] 2016-01-08 15:11
Can we reopen this ticket? I am still having the same problem. The textview is invisible for me and I can't see any of the text I type. I am able to click on the textview, but any text I type will not show up.

**Comment by danieldahan** [comment] 2016-01-08 15:13
I would need a working example to reproduce the issue. We can reopen this, but please provide something that will reproduce the issue. You can send the project to support@cosmicmind.io

Thank you!

**Comment by vishiswoz** [comment] 2016-01-08 15:36
This is the code I'm using. I can send you the full project later.

```
NSLayoutManager *layoutManager = [[NSLayoutManager alloc] init];
    NSTextContainer *textContainer = [[NSTextContainer alloc] initWithSize:self.view.bounds.size];
    text.delegate = self;
    [text.textStorage addLayoutManager:layoutManager];
    textView = [[TextView alloc] initWithTextContainer:textContainer];
    textView.delegate = self;
    textView.editable = true;
    textView.selectable = true;
    [textView setFont:[UIFont systemFontOfSize:20]];
    UILabel *label = [[UILabel alloc] init];
    [label setTextColor:[UIColor colorWithRed:158.0f/255.0f green:158.0f/255.0f blue:158.0f/255.0f alpha:1.0f]];
    [label setText:@"Choose Date"];
    [textView setPlaceholderLabel:label];
    textView.titleLabel = [[UILabel alloc] init];
    [textView.titleLabel setFont:[UIFont systemFontOfSize:12]];
    textView.titleLabelColor = [UIColor colorWithRed:224.0f/255.0f green:224.0f/255.0f blue:224.0f/255.0f alpha:1.0f];
    textView.titleLabelActiveColor = [UIColor colorWithRed:41.0f/255.0f green:121.0f/255.0f blue:255.0f/255.0f alpha:1.0f];
    textView.translatesAutoresizingMaskIntoConstraints = false;
    [MaterialLayout alignToParent:self.view child:textView top:124.0f left:24.0f bottom:24.0f right:24.0f options:0];
    [self.view addSubview:textView];
```

**Comment by danieldahan** [comment] 2016-01-08 15:38
Well I had mentioned that these two lines: 

[MaterialLayout alignToParent:self.view child:textView top:124.0f left:24.0f bottom:24.0f right:24.0f options:0];
    [self.view addSubview:textView];

need to be switched to: 

[self.view addSubview:textView];
[MaterialLayout alignToParent:self.view child:textView top:124.0f left:24.0f bottom:24.0f right:24.0f options:0];


AutoLayout does not support creating constraints prior to the view being added as a child.

**Comment by vishiswoz** [comment] 2016-01-08 15:40
Oh sorry I did that. I updated the code.

**Comment by danieldahan** [comment] 2016-01-08 15:41
So to better see the issue and help you, a reproducible project would help :)

**Comment by vishiswoz** [comment] 2016-01-08 15:42
Alright I'll do that ASAP. I'll send in about 3 hours (I'm away from my Mac right now, I'm typing this on my phone)

**Comment by danieldahan** [comment] 2016-01-08 15:43
Yes, no worries.

**Comment by vishiswoz** [comment] 2016-01-09 01:55
I sent you an email to the support email address (support@cosmicmind.io) you posted above.

**Comment by danieldahan** [comment] 2016-01-09 01:57
Yes, I received it. I will take a look :)

**Comment by danieldahan** [comment] 2016-01-09 20:03
So there were somethings you had not done in the setup. The "text" object was not initialized. The "textContainer" was not added to the layoutManager. Below is the corrected code base on what you had written. 

NSLayoutManager *layoutManager = [[NSLayoutManager alloc] init];
    NSTextContainer *textContainer = [[NSTextContainer alloc] initWithSize:self.view.bounds.size];
	[layoutManager addTextContainer:textContainer];
	
	text = [[Text alloc] init];
	text.delegate = self;
    [text.textStorage addLayoutManager:layoutManager];
	
    textView = [[TextView alloc] initWithTextContainer:textContainer];
	textView.delegate = self;
    [textView setFont:[UIFont systemFontOfSize:20]];
	
    [textView setPlaceholderLabel:[[UILabel alloc] init]];
    [[textView placeholderLabel] setTextColor:[UIColor colorWithRed:224.0f/255.0f green:224.0f/255.0f blue:224.0f/255.0f alpha:1.0f]];
    [[textView placeholderLabel] setText:@"Choose Date"];
	
	[textView setTitleLabel:[[UILabel alloc] init]];
    [textView.titleLabel setFont:[UIFont systemFontOfSize:12]];
    textView.titleLabelColor = [UIColor colorWithRed:224.0f/255.0f green:224.0f/255.0f blue:224.0f/255.0f alpha:1.0f];
    textView.titleLabelActiveColor = [UIColor colorWithRed:41.0f/255.0f green:121.0f/255.0f blue:255.0f/255.0f alpha:1.0f];
	
	[self.view addSubview:textView];
	[textView setTranslatesAutoresizingMaskIntoConstraints:NO];
	[MaterialLayout alignToParent:self.view child:textView top:300 left:10 bottom:10 right:10 options:0];

If you have any further issues, please reopen this ticket or create a new one. All the best!

**Closed by danieldahan** 2016-01-09 20:03 UTC
Labels: help wanted

**Comment by vishiswoz** [comment] 2016-01-09 21:14
Thanks, that worked. Thanks for helping me out.

Thanks a bunch,
Vishwa Iyer

On Jan 09, 2016, at 03:03 PM, Daniel Dahan <notifications@github.com> wrote:

So there were somethings you had not done in the setup. The "text" object was not initialized. The "textContainer" was not added to the layoutManager. Below is the corrected code base on what you had written.
NSLayoutManager *layoutManager = [[NSLayoutManager alloc] init];
NSTextContainer *textContainer = [[NSTextContainer alloc] initWithSize:self.view.bounds.size];
[layoutManager addTextContainer:textContainer];
text = [[Text alloc] init];
text.delegate = self;
[text.textStorage addLayoutManager:layoutManager];

textView = [[TextView alloc] initWithTextContainer:textContainer];
textView.delegate = self;
[textView setFont:[UIFont systemFontOfSize:20]];

[textView setPlaceholderLabel:[[UILabel alloc] init]];
[[textView placeholderLabel] setTextColor:[UIColor colorWithRed:224.0f/255.0f green:224.0f/255.0f blue:224.0f/255.0f alpha:1.0f]];
[[textView placeholderLabel] setText:@"Choose Date"];

[textView setTitleLabel:[[UILabel alloc] init]];
[textView.titleLabel setFont:[UIFont systemFontOfSize:12]];
textView.titleLabelColor = [UIColor colorWithRed:224.0f/255.0f green:224.0f/255.0f blue:224.0f/255.0f alpha:1.0f];
textView.titleLabelActiveColor = [UIColor colorWithRed:41.0f/255.0f green:121.0f/255.0f blue:255.0f/255.0f alpha:1.0f];

[self.view addSubview:textView];
[textView setTranslatesAutoresizingMaskIntoConstraints:NO];
[MaterialLayout alignToParent:self.view child:textView top:300 left:10 bottom:10 right:10 options:0];
If you have any further issues, please reopen this ticket or create a new one. All the best!

**Comment by danieldahan** [comment] 2016-01-09 21:15
No problem. Enjoy :)

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan
